Windows support

diff --git a/gettext-tools/tests/lang-bash b/gettext-tools/tests/lang-bash
--- a/gettext-tools/tests/lang-bash
+++ b/gettext-tools/tests/lang-bash
@@ -1,5 +1,5 @@
 #! /bin/sh
-. "${srcdir=.}/init.sh"; path_prepend_ . ../src ${top_srcdir=..}/../gettext-runtime/src
+. "${srcdir=.}/init.sh"; path_prepend_ . ../src ../../gettext-runtime/src
 
 # Test of gettext facilities in the bash language.
 # Assumes an fr_FR locale is installed.
@@ -10,6 +10,10 @@
 # output when accessing any .mo file not generated from a .po file in UTF-8
 # encoding.
 
+# This test fails if the gettext package was configured with --disable-nls,
+# because in this case the gettext-runtime/src/gettext program does not do
+# any message catalog lookups.
+
 cat <<\EOF > prog.bash
 #! /bin/bash
 
@@ -19,7 +23,7 @@ n=$1
 
 TEXTDOMAIN=prog
 export TEXTDOMAIN
-TEXTDOMAINDIR=l-bash
+TEXTDOMAINDIR=.
 export TEXTDOMAINDIR
 
 $echo $"'Your command, please?', asked the waiter."
@@ -29,14 +33,14 @@ EOF
 
 : ${XGETTEXT=xgettext}
 LC_MESSAGES=C LC_ALL= \
-${XGETTEXT} -o l-bash-prog.tmp --omit-header --no-location prog.bash \
-  >l-bash-prog.err 2>&1
+${XGETTEXT} -o prog.tmp --omit-header --no-location prog.bash \
+  >prog.err 2>&1
 result=$?
-cat l-bash-prog.err | grep -v 'warning: the syntax \$"\.\.\." is deprecated due to security reasons'
-test $result = 0 || { exit 1; }
-LC_ALL=C tr -d '\r' < l-bash-prog.tmp > l-bash-prog.pot || exit 1
+cat prog.err | grep -v 'warning: the syntax \$"\.\.\." is deprecated due to security reasons'
+test $result = 0 || { Exit 1; }
+LC_ALL=C tr -d '\r' < prog.tmp > prog.pot || Exit 1
 
-cat <<\EOF > l-bash-prog.ok
+cat <<\EOF > prog.ok
 msgid "'Your command, please?', asked the waiter."
 msgstr ""
 
@@ -48,9 +52,9 @@ msgstr[1] ""
 EOF
 
 : ${DIFF=diff}
-${DIFF} l-bash-prog.ok l-bash-prog.pot || exit 1
+${DIFF} prog.ok prog.pot || Exit 1
 
-cat <<\EOF > l-bash-fr.po
+cat <<\EOF > fr.po
 msgid ""
 msgstr ""
 "Content-Type: text/plain; charset=ISO-8859-1\n"
@@ -68,25 +72,24 @@ msgstr[1] "$n morceaux de gateau"
 EOF
 
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o l-bash-fr.po.tmp l-bash-fr.po l-bash-prog.pot || exit 1
-LC_ALL=C tr -d '\r' < l-bash-fr.po.tmp > l-bash-fr.po.new || exit 1
+${MSGMERGE} -q -o fr.po.tmp fr.po prog.pot || Exit 1
+LC_ALL=C tr -d '\r' < fr.po.tmp > fr.po.new || Exit 1
 
 : ${DIFF=diff}
-${DIFF} l-bash-fr.po l-bash-fr.po.new || exit 1
+${DIFF} fr.po fr.po.new || Exit 1
 
-test -d l-bash || mkdir l-bash
-test -d l-bash/fr || mkdir l-bash/fr
-test -d l-bash/fr/LC_MESSAGES || mkdir l-bash/fr/LC_MESSAGES
+test -d fr || mkdir fr
+test -d fr/LC_MESSAGES || mkdir fr/LC_MESSAGES
 
 : ${MSGFMT=msgfmt}
-${MSGFMT} -o l-bash/fr/LC_MESSAGES/prog.mo l-bash-fr.po
+${MSGFMT} -o fr/LC_MESSAGES/prog.mo fr.po
 
 # Test for presence of bash version 2.0 or newer.
 (bash -c :) >/dev/null 2>/dev/null \
-  || { echo "Skipping test: bash not found"; exit 77; }
+  || { echo "Skipping test: bash not found"; Exit 77; }
 case `bash -c 'echo $BASH_VERSION'` in
   [2-9].*) ;;
-  *) echo "Skipping test: bash version too old"; exit 77;;
+  *) echo "Skipping test: bash version too old"; Exit 77;;
 esac
 
 # Test which of the fr_FR locales are installed.
@@ -97,7 +100,7 @@ if test $LOCALE_FR != none; then
   case $? in
     0) ;;
     77) LOCALE_FR=none;;
-    *) exit 1;;
+    *) Exit 1;;
   esac
 fi
 if test $LOCALE_FR_UTF8 != none; then
@@ -105,7 +108,7 @@ if test $LOCALE_FR_UTF8 != none; then
   case $? in
     0) ;;
     77) LOCALE_FR_UTF8=none;;
-    *) exit 1;;
+    *) Exit 1;;
   esac
 fi
 if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
@@ -114,20 +117,33 @@ if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
   else
     echo "Skipping test: no french locale is supported"
   fi
-  exit 77
+  Exit 77
 fi
 
+case "$host_os" in
+  darwin*)
+    if test $LOCALE_FR != none; then
+      LC_ALL=$LOCALE_FR bash --help \
+        | grep '^Utilisation' > /dev/null 2>&1 || Exit 77
+    fi
+    if test $LOCALE_FR_UTF8 != none; then
+      LC_ALL=$LOCALE_FR_UTF8 bash --help \
+        | grep '^Utilisation' > /dev/null 2>&1 || Exit 77
+    fi
+  ;;
+esac
+
 # Expected result when bash is built without i18n support.
-cat <<\EOF > l-bash-prog.nok
+cat <<\EOF > prog.nok
 'Your command, please?', asked the waiter.
 2 morceaux de gateau
 EOF
 # Expected result when bash is built with i18n support.
-cat <<\EOF > l-bash-prog.ok
+cat <<\EOF > prog.ok
 «Votre commande, s'il vous plait», dit le garçon.
 2 morceaux de gateau
 EOF
-cat <<\EOF > l-bash-prog.oku
+cat <<\EOF > prog.oku
 Â«Votre commande, s'il vous plaitÂ», dit le garÃ§on.
 2 morceaux de gateau
 EOF
@@ -135,22 +151,24 @@ EOF
 : ${LOCALE_FR=fr_FR}
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
-  LANGUAGE= LC_ALL=$LOCALE_FR bash ./prog.bash 2 > l-bash-prog.out || exit 1
+  prepare_locale_ fr $LOCALE_FR
+  LANGUAGE= LC_ALL=$LOCALE_FR bash ./prog.bash 2 > prog.out || Exit 1
   : ${DIFF=diff}
-  ${DIFF} l-bash-prog.nok l-bash-prog.out > /dev/null && {
+  ${DIFF} prog.nok prog.out > /dev/null && {
     echo "Skipping test: bash is built without i18n support"
-    exit 77
+    Exit 77
   }
-  ${DIFF} l-bash-prog.ok l-bash-prog.out || exit 1
+  ${DIFF} prog.ok prog.out || Exit 1
 fi
 if test $LOCALE_FR_UTF8 != none; then
-  LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 bash ./prog.bash 2 > l-bash-prog.out || exit 1
+  prepare_locale_ fr $LOCALE_FR_UTF8
+  LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 bash ./prog.bash 2 > prog.out || Exit 1
   : ${DIFF=diff}
-  ${DIFF} l-bash-prog.nok l-bash-prog.out > /dev/null && {
+  ${DIFF} prog.nok prog.out > /dev/null && {
     echo "Skipping test: bash is built without i18n support"
-    exit 77
+    Exit 77
   }
-  ${DIFF} l-bash-prog.oku l-bash-prog.out || exit 1
+  ${DIFF} prog.oku prog.out || Exit 1
 fi
 
-exit 0
+Exit 0
diff --git a/gettext-tools/tests/lang-clisp b/gettext-tools/tests/lang-clisp
--- a/gettext-tools/tests/lang-clisp
+++ b/gettext-tools/tests/lang-clisp
@@ -7,7 +7,7 @@
 
 cat <<\EOF > prog.lisp
 (setf (textdomain) "prog")
-(setf (textdomaindir "prog") "./l-clisp/")
+(setf (textdomaindir "prog") "./")
 
 (setq n (parse-integer (first *args*)))
 
@@ -19,10 +19,10 @@ cat <<\EOF > prog.lisp
 EOF
 
 : ${XGETTEXT=xgettext}
-${XGETTEXT} -o l-clisp-prog.tmp --omit-header --no-location prog.lisp || exit 1
-LC_ALL=C tr -d '\r' < l-clisp-prog.tmp > l-clisp-prog.pot || exit 1
+${XGETTEXT} -o prog.tmp --omit-header --no-location prog.lisp || Exit 1
+LC_ALL=C tr -d '\r' < prog.tmp > prog.pot || Exit 1
 
-cat <<EOF > l-clisp-prog.ok
+cat <<EOF > prog.ok
 msgid "'Your command, please?', asked the waiter."
 msgstr ""
 
@@ -38,9 +38,9 @@ msgstr ""
 EOF
 
 : ${DIFF=diff}
-${DIFF} l-clisp-prog.ok l-clisp-prog.pot || exit 1
+${DIFF} prog.ok prog.pot || Exit 1
 
-cat <<\EOF > l-clisp-fr.po
+cat <<\EOF > fr.po
 msgid ""
 msgstr ""
 "Content-Type: text/plain; charset=ISO-8859-1\n"
@@ -63,34 +63,33 @@ msgstr "~1@*~A remplace ~0@*~A."
 EOF
 
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o l-clisp-fr.po.tmp l-clisp-fr.po l-clisp-prog.pot || exit 1
-LC_ALL=C tr -d '\r' < l-clisp-fr.po.tmp > l-clisp-fr.po.new || exit 1
+${MSGMERGE} -q -o fr.po.tmp fr.po prog.pot || Exit 1
+LC_ALL=C tr -d '\r' < fr.po.tmp > fr.po.new || Exit 1
 
 : ${DIFF=diff}
-${DIFF} l-clisp-fr.po l-clisp-fr.po.new || exit 1
+${DIFF} fr.po fr.po.new || Exit 1
 
-test -d l-clisp || mkdir l-clisp
-test -d l-clisp/fr || mkdir l-clisp/fr
-test -d l-clisp/fr/LC_MESSAGES || mkdir l-clisp/fr/LC_MESSAGES
+test -d fr || mkdir fr
+test -d fr/LC_MESSAGES || mkdir fr/LC_MESSAGES
 
 : ${MSGFMT=msgfmt}
-${MSGFMT} -o l-clisp/fr/LC_MESSAGES/prog.mo l-clisp-fr.po
+${MSGFMT} -o fr/LC_MESSAGES/prog.mo fr.po
 
 # Test for presence of clisp version 2.28 or newer with gettext support.
 # Use clisp for the comparison of the version numbers; neither 'expr' nor 'bc'
 # can deal with floating-point numbers.
 (clisp --version) >/dev/null 2>/dev/null \
-  || { echo "Skipping test: clisp not found"; exit 77; }
+  || { echo "Skipping test: clisp not found"; Exit 77; }
 version=`clisp --version | sed -n -e 1p | sed -e 's/^[^0-9]*//'`
 case $version in
   19* | 20*) # older than 2.25
-    echo "Skipping test: clisp version too old"; exit 77;;
+    echo "Skipping test: clisp version too old"; Exit 77;;
 esac
 version=`echo $version | sed -e 's/^\([0-9]*\.[0-9]*\).*/\1/'`
 clisp -norc -x "(sys::exit #+GETTEXT (not (>= $version 2.28)) #-GETTEXT t)" \
       >/dev/null \
   || { echo "Skipping test: clisp was built without gettext support"
-       exit 77
+       Exit 77
      }
 
 # Test which of the fr_FR locales are installed.
@@ -101,7 +100,7 @@ if test $LOCALE_FR != none; then
   case $? in
     0) ;;
     77) LOCALE_FR=none;;
-    *) exit 1;;
+    *) Exit 1;;
   esac
 fi
 if test $LOCALE_FR_UTF8 != none; then
@@ -109,7 +108,7 @@ if test $LOCALE_FR_UTF8 != none; then
   case $? in
     0) ;;
     77) LOCALE_FR_UTF8=none;;
-    *) exit 1;;
+    *) Exit 1;;
   esac
 fi
 if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
@@ -118,16 +117,16 @@ if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
   else
     echo "Skipping test: no french locale is supported"
   fi
-  exit 77
+  Exit 77
 fi
 
 : ${DIFF=diff}
-cat <<\EOF > l-clisp-prog.ok
+cat <<\EOF > prog.ok
 «Votre commande, s'il vous plait», dit le garçon.
 2 morceaux de gateau
 EUR remplace FF.
 EOF
-cat <<\EOF > l-clisp-prog.oku
+cat <<\EOF > prog.oku
 Â«Votre commande, s'il vous plaitÂ», dit le garÃ§on.
 2 morceaux de gateau
 EUR remplace FF.
@@ -136,14 +135,16 @@ EOF
 : ${LOCALE_FR=fr_FR}
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
-  CLISP_LANGUAGE= LANGUAGE= LC_ALL=$LOCALE_FR clisp prog.lisp 2 > l-clisp-prog.tmp || exit 1
-  LC_ALL=C tr -d '\r' < l-clisp-prog.tmp > l-clisp-prog.out || exit 1
-  ${DIFF} l-clisp-prog.ok l-clisp-prog.out || exit 1
+  prepare_locale_ fr $LOCALE_FR
+  CLISP_LANGUAGE= LANGUAGE= LC_ALL=$LOCALE_FR clisp prog.lisp 2 > prog.tmp || Exit 1
+  LC_ALL=C tr -d '\r' < prog.tmp > prog.out || Exit 1
+  ${DIFF} prog.ok prog.out || Exit 1
 fi
 if test $LOCALE_FR_UTF8 != none; then
-  CLISP_LANGUAGE= LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 clisp prog.lisp 2 > l-clisp-prog.tmp || exit 1
-  LC_ALL=C tr -d '\r' < l-clisp-prog.tmp > l-clisp-prog.out || exit 1
-  ${DIFF} l-clisp-prog.oku l-clisp-prog.out || exit 1
+  prepare_locale_ fr $LOCALE_FR_UTF8
+  CLISP_LANGUAGE= LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 clisp prog.lisp 2 > prog.tmp || Exit 1
+  LC_ALL=C tr -d '\r' < prog.tmp > prog.out || Exit 1
+  ${DIFF} prog.oku prog.out || Exit 1
 fi
 
-exit 0
+Exit 0
diff --git a/gettext-tools/tests/lang-librep b/gettext-tools/tests/lang-librep
--- a/gettext-tools/tests/lang-librep
+++ b/gettext-tools/tests/lang-librep
@@ -9,7 +9,7 @@ cat <<\EOF > prog.jl
 (require 'rep.i18n.gettext)
 
 (textdomain "prog")
-(bindtextdomain "prog" "l-librep")
+(bindtextdomain "prog" ".")
 
 (format standard-output "%s\n" (_ "'Your command, please?', asked the waiter."))
 
@@ -18,10 +18,10 @@ cat <<\EOF > prog.jl
 EOF
 
 : ${XGETTEXT=xgettext}
-${XGETTEXT} -o l-librep-prog.tmp --omit-header --no-location prog.jl || exit 1
-LC_ALL=C tr -d '\r' < l-librep-prog.tmp > l-librep-prog.pot || exit 1
+${XGETTEXT} -o prog.tmp --omit-header --no-location prog.jl || Exit 1
+LC_ALL=C tr -d '\r' < prog.tmp > prog.pot || Exit 1
 
-cat <<EOF > l-librep-prog.ok
+cat <<EOF > prog.ok
 msgid "'Your command, please?', asked the waiter."
 msgstr ""
 
@@ -31,9 +31,9 @@ msgstr ""
 EOF
 
 : ${DIFF=diff}
-${DIFF} l-librep-prog.ok l-librep-prog.pot || exit 1
+${DIFF} prog.ok prog.pot || Exit 1
 
-cat <<\EOF > l-librep-fr.po
+cat <<\EOF > fr.po
 msgid ""
 msgstr ""
 "Content-Type: text/plain; charset=ISO-8859-1\n"
@@ -49,25 +49,24 @@ msgstr "%2$s remplace %1$s."
 EOF
 
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o l-librep-fr.po.tmp l-librep-fr.po l-librep-prog.pot || exit 1
-LC_ALL=C tr -d '\r' < l-librep-fr.po.tmp > l-librep-fr.po.new || exit 1
+${MSGMERGE} -q -o fr.po.tmp fr.po prog.pot || Exit 1
+LC_ALL=C tr -d '\r' < fr.po.tmp > fr.po.new || Exit 1
 
 : ${DIFF=diff}
-${DIFF} l-librep-fr.po l-librep-fr.po.new || exit 1
+${DIFF} fr.po fr.po.new || Exit 1
 
-test -d l-librep || mkdir l-librep
-test -d l-librep/fr || mkdir l-librep/fr
-test -d l-librep/fr/LC_MESSAGES || mkdir l-librep/fr/LC_MESSAGES
+test -d fr || mkdir fr
+test -d fr/LC_MESSAGES || mkdir fr/LC_MESSAGES
 
 : ${MSGFMT=msgfmt}
-${MSGFMT} -o l-librep/fr/LC_MESSAGES/prog.mo l-librep-fr.po
+${MSGFMT} -o fr/LC_MESSAGES/prog.mo fr.po
 
 # Test for presence of rep version 0.15.3 or newer.
 (rep --version) >/dev/null 2>/dev/null \
-  || { echo "Skipping test: rep not found"; exit 77; }
+  || { echo "Skipping test: rep not found"; Exit 77; }
 case `rep --version | sed -e 's/^[^0-9]*//'` in
   0.[0-9] | 0.1[0-5] | 0.[0-9].* | 0.1[0-4].* | 0.15.[0-2] )
-    echo "Skipping test: rep version too old"; exit 77;;
+    echo "Skipping test: rep version too old"; Exit 77;;
 esac
 
 # Test which of the fr_FR locales are installed.
@@ -78,7 +77,7 @@ if test $LOCALE_FR != none; then
   case $? in
     0) ;;
     77) LOCALE_FR=none;;
-    *) exit 1;;
+    *) Exit 1;;
   esac
 fi
 if test $LOCALE_FR_UTF8 != none; then
@@ -86,7 +85,7 @@ if test $LOCALE_FR_UTF8 != none; then
   case $? in
     0) ;;
     77) LOCALE_FR_UTF8=none;;
-    *) exit 1;;
+    *) Exit 1;;
   esac
 fi
 if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
@@ -95,15 +94,15 @@ if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
   else
     echo "Skipping test: no french locale is supported"
   fi
-  exit 77
+  Exit 77
 fi
 
 : ${DIFF=diff}
-cat <<\EOF > l-librep-prog.ok
+cat <<\EOF > prog.ok
 «Votre commande, s'il vous plait», dit le garçon.
 EUR remplace FF.
 EOF
-cat <<\EOF > l-librep-prog.oku
+cat <<\EOF > prog.oku
 Â«Votre commande, s'il vous plaitÂ», dit le garÃ§on.
 EUR remplace FF.
 EOF
@@ -111,12 +110,14 @@ EOF
 : ${LOCALE_FR=fr_FR}
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
-  LANGUAGE= LC_ALL=$LOCALE_FR rep --no-rc --batch prog.jl > l-librep-prog.out || exit 1
-  ${DIFF} l-librep-prog.ok l-librep-prog.out || exit 1
+  prepare_locale_ fr $LOCALE_FR
+  LANGUAGE= LC_ALL=$LOCALE_FR rep --no-rc --batch prog.jl > prog.out || Exit 1
+  ${DIFF} prog.ok prog.out || Exit 1
 fi
 if test $LOCALE_FR_UTF8 != none; then
-  LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 rep --no-rc --batch prog.jl > l-librep-prog.out || exit 1
-  ${DIFF} l-librep-prog.oku l-librep-prog.out || exit 1
+  prepare_locale_ fr $LOCALE_FR_UTF8
+  LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 rep --no-rc --batch prog.jl > prog.out || Exit 1
+  ${DIFF} prog.oku prog.out || Exit 1
 fi
 
-exit 0
+Exit 0
diff --git a/gettext-tools/tests/lang-lua b/gettext-tools/tests/lang-lua
--- a/gettext-tools/tests/lang-lua
+++ b/gettext-tools/tests/lang-lua
@@ -7,7 +7,7 @@
 
 cat <<\EOF > prog.lua
 require("gettext")
-gettext.bindtextdomain("prog", "l-lua")
+gettext.bindtextdomain("prog", ".")
 gettext.textdomain("prog")
 _ = gettext.gettext
 n = 42
@@ -18,10 +18,10 @@ print(string.format(_[==[%s is replaced by %s.]==], "FF", "EUR"))
 EOF
 
 : ${XGETTEXT=xgettext}
-${XGETTEXT} -o l-lua-prog.tmp --omit-header --no-location prog.lua || exit 1
-LC_ALL=C tr -d '\r' < l-lua-prog.tmp > l-lua-prog.pot || exit 1
+${XGETTEXT} -o prog.tmp --omit-header --no-location prog.lua || Exit 1
+LC_ALL=C tr -d '\r' < prog.tmp > prog.pot || Exit 1
 
-cat <<\EOF > l-lua-prog.ok
+cat <<\EOF > prog.ok
 msgid "'Your command, please?', asked the waiter."
 msgstr ""
 
@@ -37,9 +37,9 @@ msgstr ""
 EOF
 
 : ${DIFF=diff}
-${DIFF} l-lua-prog.ok l-lua-prog.pot || exit 1
+${DIFF} prog.ok prog.pot || Exit 1
 
-cat <<\EOF > l-lua-fr.po
+cat <<\EOF > fr.po
 msgid ""
 msgstr ""
 "Content-Type: text/plain; charset=ISO-8859-1\n"
@@ -60,30 +60,29 @@ msgstr "%s remplace %s."
 EOF
 
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o l-lua-fr.po.tmp l-lua-fr.po l-lua-prog.pot || exit 1
-LC_ALL=C tr -d '\r' < l-lua-fr.po.tmp > l-lua-fr.po.new || exit 1
+${MSGMERGE} -q -o fr.po.tmp fr.po prog.pot || Exit 1
+LC_ALL=C tr -d '\r' < fr.po.tmp > fr.po.new || Exit 1
 
 : ${DIFF=diff}
-${DIFF} l-lua-fr.po l-lua-fr.po.new || exit 1
+${DIFF} fr.po fr.po.new || Exit 1
 
-test -d l-lua || mkdir l-lua
-test -d l-lua/fr || mkdir l-lua/fr
-test -d l-lua/fr/LC_MESSAGES || mkdir l-lua/fr/LC_MESSAGES
+test -d fr || mkdir fr
+test -d fr/LC_MESSAGES || mkdir fr/LC_MESSAGES
 
 : ${MSGFMT=msgfmt}
-${MSGFMT} -o l-lua/fr/LC_MESSAGES/prog.mo l-lua-fr.po
+${MSGFMT} -o fr/LC_MESSAGES/prog.mo fr.po
 
 # Test for presence of lua version 5.0 or newer with gettext support.
 (lua -v) >/dev/null 2>/dev/null
 test $? -le 1 \
-  || { echo "Skipping test: lua not found"; exit 77; }
+  || { echo "Skipping test: lua not found"; Exit 77; }
 case `lua -v 2>&1 | sed -e 's/^[^0-9]*//'` in
   [5-9].*) ;;
-  *) echo "Skipping test: lua version too old"; exit 77;;
+  *) echo "Skipping test: lua version too old"; Exit 77;;
 esac
 { lua -v -l gettext > /dev/null 2>/dev/null; } \
   || { echo "Skipping test: lua gettext module not found"
-       exit 77
+       Exit 77
      }
 
 # Test which of the fr_FR locales are installed.
@@ -94,7 +93,7 @@ if test $LOCALE_FR != none; then
   case $? in
     0) ;;
     77) LOCALE_FR=none;;
-    *) exit 1;;
+    *) Exit 1;;
   esac
 fi
 if test $LOCALE_FR_UTF8 != none; then
@@ -102,7 +101,7 @@ if test $LOCALE_FR_UTF8 != none; then
   case $? in
     0) ;;
     77) LOCALE_FR_UTF8=none;;
-    *) exit 1;;
+    *) Exit 1;;
   esac
 fi
 if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
@@ -111,16 +110,16 @@ if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
   else
     echo "Skipping test: no french locale is supported"
   fi
-  exit 77
+  Exit 77
 fi
 
 : ${DIFF=diff}
-cat <<\EOF > l-lua-prog.ok
+cat <<\EOF > prog.ok
 «Votre commande, s'il vous plait», dit le garçon.
 42 morceaux de gateau
 FF remplace EUR.
 EOF
-cat <<\EOF > l-lua-prog.oku
+cat <<\EOF > prog.oku
 Â«Votre commande, s'il vous plaitÂ», dit le garÃ§on.
 42 morceaux de gateau
 FF remplace EUR.
@@ -129,12 +128,14 @@ EOF
 : ${LOCALE_FR=fr_FR}
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
-  LANGUAGE= LC_ALL=$LOCALE_FR lua -l gettext prog.lua > l-lua-prog.out || exit 1
-  ${DIFF} l-lua-prog.ok l-lua-prog.out || exit 1
+  prepare_locale_ fr $LOCALE_FR
+  LANGUAGE= LC_ALL=$LOCALE_FR lua -l gettext prog.lua > prog.out || Exit 1
+  ${DIFF} prog.ok prog.out || Exit 1
 fi
 if test $LOCALE_FR_UTF8 != none; then
-  LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 lua -l gettext prog.lua > l-lua-prog.out || exit 1
-  ${DIFF} l-lua-prog.oku l-lua-prog.out || exit 1
+  prepare_locale_ fr $LOCALE_FR_UTF8
+  LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 lua -l gettext prog.lua > prog.out || Exit 1
+  ${DIFF} prog.oku prog.out || Exit 1
 fi
 
-exit 0
+Exit 0
diff --git a/gettext-tools/tests/lang-python-1 b/gettext-tools/tests/lang-python-1
--- a/gettext-tools/tests/lang-python-1
+++ b/gettext-tools/tests/lang-python-1
@@ -3,7 +3,7 @@
 
 # Test of gettext facilities in the Python language.
 
-# Note: This test fails with Python 2.3, 2.4 when an UTF-8 locale is present.
+# Note: This test fails with Python 2.3 ... 2.7 when an UTF-8 locale is present.
 # It looks like a bug in Python's gettext.py. This here is a quick workaround:
 UTF8_LOCALE_UNSUPPORTED=yes
 
@@ -11,7 +11,7 @@ cat <<\EOF > prog1.py
 import gettext
 
 gettext.textdomain('prog')
-gettext.bindtextdomain('prog', 'l-python-1')
+gettext.bindtextdomain('prog', '.')
 
 print gettext.gettext("'Your command, please?', asked the waiter.")
 print gettext.gettext("%(oldCurrency)s is replaced by %(newCurrency)s.") \
@@ -19,10 +19,10 @@ print gettext.gettext("%(oldCurrency)s is replaced by %(newCurrency)s.") \
 EOF
 
 : ${XGETTEXT=xgettext}
-${XGETTEXT} -o l-python-1-prog.tmp --omit-header --no-location prog1.py || exit 1
-LC_ALL=C tr -d '\r' < l-python-1-prog.tmp > l-python-1-prog.pot || exit 1
+${XGETTEXT} -o prog.tmp --omit-header --no-location prog1.py || Exit 1
+LC_ALL=C tr -d '\r' < prog.tmp > prog.pot || Exit 1
 
-cat <<EOF > l-python-1-prog.ok
+cat <<EOF > prog.ok
 msgid "'Your command, please?', asked the waiter."
 msgstr ""
 
@@ -32,9 +32,9 @@ msgstr ""
 EOF
 
 : ${DIFF=diff}
-${DIFF} l-python-1-prog.ok l-python-1-prog.pot || exit 1
+${DIFF} prog.ok prog.pot || Exit 1
 
-cat <<\EOF > l-python-1-fr.po
+cat <<\EOF > fr.po
 msgid ""
 msgstr ""
 "Content-Type: text/plain; charset=ISO-8859-1\n"
@@ -50,33 +50,32 @@ msgstr "%(newCurrency)s remplace %(oldCurrency)s."
 EOF
 
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o l-python-1-fr.po.tmp l-python-1-fr.po l-python-1-prog.pot || exit 1
-LC_ALL=C tr -d '\r' < l-python-1-fr.po.tmp > l-python-1-fr.po.new || exit 1
+${MSGMERGE} -q -o fr.po.tmp fr.po prog.pot || Exit 1
+LC_ALL=C tr -d '\r' < fr.po.tmp > fr.po.new || Exit 1
 
 : ${DIFF=diff}
-${DIFF} l-python-1-fr.po l-python-1-fr.po.new || exit 1
+${DIFF} fr.po fr.po.new || Exit 1
 
-test -d l-python-1 || mkdir l-python-1
-test -d l-python-1/fr || mkdir l-python-1/fr
-test -d l-python-1/fr/LC_MESSAGES || mkdir l-python-1/fr/LC_MESSAGES
+test -d fr || mkdir fr
+test -d fr/LC_MESSAGES || mkdir fr/LC_MESSAGES
 
 : ${MSGFMT=msgfmt}
-${MSGFMT} -o l-python-1/fr/LC_MESSAGES/prog.mo l-python-1-fr.po
+${MSGFMT} -o fr/LC_MESSAGES/prog.mo fr.po
 
 # Test for presence of python version 2.0 or newer.
 (python -V) >/dev/null 2>/dev/null \
-  || { echo "Skipping test: python not found"; exit 77; }
+  || { echo "Skipping test: python not found"; Exit 77; }
 case `python -c 'import sys; print sys.hexversion >= 0x20000F0'` in
   1 | True) ;;
-  *) echo "Skipping test: python version too old"; exit 77;;
+  *) echo "Skipping test: python version too old"; Exit 77;;
 esac
 
 : ${DIFF=diff}
-cat <<\EOF > l-python-1-prog.ok
+cat <<\EOF > prog.ok
 «Votre commande, s'il vous plait», dit le garçon.
 EUR remplace FF.
 EOF
-cat <<\EOF > l-python-1-prog.oku
+cat <<\EOF > prog.oku
 Â«Votre commande, s'il vous plaitÂ», dit le garÃ§on.
 EUR remplace FF.
 EOF
@@ -84,13 +83,15 @@ EOF
 : ${LOCALE_FR=fr_FR}
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
-  LANGUAGE= LC_ALL=$LOCALE_FR python prog1.py > l-python-1-prog.out || exit 1
-  ${DIFF} l-python-1-prog.ok l-python-1-prog.out || exit 1
+  prepare_locale_ fr $LOCALE_FR
+  LANGUAGE= LC_ALL=$LOCALE_FR python prog1.py > prog.out || Exit 1
+  ${DIFF} prog.ok prog.out || Exit 1
 fi
 if test -z "$UTF8_LOCALE_UNSUPPORTED"; then
   if test $LOCALE_FR_UTF8 != none; then
-    LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 python prog1.py > l-python-1-prog.out || exit 1
-    ${DIFF} l-python-1-prog.oku l-python-1-prog.out || exit 1
+    prepare_locale_ fr $LOCALE_FR_UTF8
+    LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 python prog1.py > prog.out || Exit 1
+    ${DIFF} prog.oku prog.out || Exit 1
   fi
   if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
     if test -f /usr/bin/localedef; then
@@ -98,7 +99,7 @@ if test -z "$UTF8_LOCALE_UNSUPPORTED"; then
     else
       echo "Skipping test: no french locale is supported"
     fi
-    exit 77
+    Exit 77
   fi
 else
   if test $LOCALE_FR = none; then
@@ -107,8 +108,8 @@ else
     else
       echo "Skipping test: no traditional french locale is supported"
     fi
-    exit 77
+    Exit 77
   fi
 fi
 
-exit 0
+Exit 0
